name: Publish Modpack

on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip -r modpack.zip . -x "*.git*"
      - run: echo "VERSION=$(cat manifest.json | jq -r '.version_number')" >> $GITHUB_OUTPUT
        id: version
      - uses: GreenTF/upload-thunderstore-package@v4
        with:
          namespace: Cutie
          description: a modpack
          token: ${{ secrets.THUNDERSTORE }}
          name: anti_paradise
          version: ${{ steps.version.outputs.VERSION }}
          community: lethal-company
          categories: |
            modpacks
          file: modpack.zip
