name: Publish Mod

# Run when a new release is... released
on: 
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4
        with:
          namespace: Cutie # the thunderstore 'team' to publish under
          description: a modpack
          token: ${{ secrets.YOUR_TOKEN_NAME }}
          name: anti_paradise # the name of the package
          version: $GITHUB_REF_NAME # Use the tag as the package version
          community: lethal-company
          repo: thunderstore.io
          categories: | # <-- notice this pipe character
            Modpack
